@college_record_keeper_backend_HostAddress = http://localhost:5151

###
GET {{college_record_keeper_backend_HostAddress}}/student/033816f9-0914-4ff6-9e6c-bca0780eec33
Accept: application/json

###
POST {{college_record_keeper_backend_HostAddress}}/student
Content-Type: application/json

{
    "FirstName":"Joe",
    "LastName":"Baz",
    "CetPercentile":99.99,
    "hscPercentage":70.99,
    "sscPercentage":96.20,
    "dob":"2001-01-06T17:16:40",
    "yearOfAdmission":"2021-01-06T17:16:40"
}
